import Head from "next/head";
import { Inter } from "next/font/google";
import { GetStaticProps } from "next";
import { booksServices } from "~/libs/supabase/services";
import { useQuery } from "@tanstack/react-query";
import { Layout, List, Typography } from "antd";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  books: Awaited<ReturnType<typeof booksServices.getMany>>;
}

function Home({ books: initialBooks }: Props) {
  const { data: books } = useQuery(["books"], () => booksServices.getMany(), {
    initialData: initialBooks,
    staleTime: 1000 * 60 * 60 * 24,
  });

  console.log(books);

  return (
    <>
      <Head>
        <title>Bookshelf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Layout>
          <Layout.Header
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              background: "#fff",
            }}
          >
            <Typography.Title
              style={{
                margin: 0,
              }}
              level={3}
            >
              Bookshelf
            </Typography.Title>
          </Layout.Header>
          <Layout.Content style={{ padding: "1rem" }}>
            <List
              dataSource={books}
              renderItem={(item) => (
                <List.Item>
                  <List.Item.Meta
                    title={item.title}
                    description={item.description}
                  />
                </List.Item>
              )}
            />
          </Layout.Content>
        </Layout>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const books = await booksServices.getMany();

  return {
    props: { books },
  };
};

export default Home;
